name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: pwd
      run: |
        pwd
        cd ..
        pwd
        whoami
        export
    - name: Run
      run: python go-dutch.py 
